Vagrant.configure("2") do |config|
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder "config/", "/opt/config"
  config.vm.synced_folder "../scripts", "/opt/scripts"
  
  config.vm.box = "phusion/ubuntu-14.04-amd64"
  config.vm.hostname = "dbserver"
  
	config.vm.provision "docker" do |d|
		d.pull_images "ubuntu"
		d.pull_images "mysql"
		d.pull_images "mysql/mysql-server"
		d.pull_images "progrium/consul"
		d.pull_images "gliderlabs/registrator"
		
		d.run "mysql_server",
			image: "mysql:latest",
			args: "-p 3306:3306 -v /opt/config:/opt/config -v /opt/scripts:/opt/scripts -e MYSQL_ROOT_PASSWORD=Gnleln_2"
						
			
		d.run "mysql_client",
			image: "mysql:latest",
			args: '--link mysql_server:mysql_client -v /opt/config:/opt/config -v /opt/scripts:/opt/scripts',
			cmd: 'sh -c /opt/scripts/startdb.sh',
			daemonize: false
		
		
	end
	
end
