Vagrant.configure("2") do |config|
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder "config/", "/opt/config"
  config.vm.synced_folder "../scripts", "/opt/scripts"
  
  config.vm.box = "phusion/ubuntu-14.04-amd64"
  config.vm.hostname = "dbserver"
  
	config.vm.provision "docker" do |d|
		d.pull_images "mysql"
		d.pull_images "progrium/consul"
		d.pull_images "gliderlabs/registrator"
	end
	
end
