Vagrant.configure("2") do |config|
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder "webapp/", "/opt/webapp"
  config.vm.box = "phusion/ubuntu-14.04-amd64"
  config.vm.synced_folder "../scripts", "/opt/scripts"
  
  config.vm.hostname = "webserver"
	config.vm.provision "docker" do |d|
		d.pull_images "ubuntu"
		d.pull_images "richarvey/nginx-php-fpm"
		d.pull_images "progrium/consul"
		d.pull_images "gliderlabs/registrator"
		
		d.run "richarvey/nginx-php-fpm",
			args:"-p 8080:80 -v /opt/webapp:/usr/share/nginx/html"
	end
end